name: Deploy to InfinityFree

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    name: Upload perubahan lewat FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Sesuaikan kalau folder root FTP InfinityFree Anda bukan langsung htdocs
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/database/**
            **/.gitignore
            includes/db.config.php
